### PR TITLE
Add staticcheck CI with refactor

### PR DESCRIPTION
**Pull request by julian-bcw**
**Detailed description**:
This PR does two things:
1. Introduces a static analysis pipeline to help prevent potential bugs and security vulnerabilities in the future.
Specifically, this will check for things like deprecated packages, dead code, and inefficient/redundant function calls and expressions.
2. Refactors the existing code to resolve any alarms.
    - Most of these changes are simplifications and dead code elimination, though there was also a deprecated package in the test cases, as well as an inefficient string comparison. Overall, low priority fixes.

A complete list of the checks in this pipeline can be found [here](https://staticcheck.io/docs/checks), though I have removed the style checks (ST*) as well as a few “code simplifications” (S1002, S1005, S1008, S1023, S1039) that are more like style preferences.

EDIT: I've also removed check U1000 (no unused variables), because it was causing the E2E tests to fail. I suspect that there was a false alarm. Perhaps a struct needs to be in a certain format to be converted to a JSON or something.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Review by rokn — DISMISSED** [review]

**Review by svetlio8 — DISMISSED** [review]

**Review by Psykepro — APPROVED** [review]

**Review by svetlio8 — COMMENTED** [review]
Could you please sign your commits? It is part of the checks.

**Comment by julian-bcw** [comment]
@svetlio8 This is strange. All of the commits are signed already. Should I just close this PR and reopen?

**Comment by failfmi** [comment]
> @svetlio8 This is strange. All of the commits are signed already. Should I just close this PR and reopen?

@julian-bcw 
Sign-offs and signed commits are two different things:
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by julian-bcw** [comment]
@failfmi Ah, thanks for the explanation! I've signed the commits, and force-pushed.

**Review by svetlio8 — APPROVED** [review]

**Pull request merged**
